### ISSUE TITLE
SSR: results are always from globally configured channel, not from SalesChannel-individually configured channel

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#107]
We are working with ssr-branch, currently 23b549217b90880e096f8882e6358c25d8739a2b on Shopware 6.4.12.0

SSR search (navigation) requests are always fired against the FF channel defined for all saleschannels.
We have different FF channels defined for different saleschannels which are ignored.

The problematic code line seems to bee:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/23b549217b90880e096f8882e6358c25d8739a2b/src/Utilites/Ssr/SearchAdapter.php#L54

The line misses the saleschannelId as parameter.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann thank you for reporting. Solution has been pushed to ssr-branch. Please let me know in case of any further problems.

**Comment by SvenHerrmann** [comment]
Thanks @grzegorz-jamroz , it works for us :-)
