### ISSUE TITLE
SSR: how to mix mustache and twig?

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#110]
We are working with ssr-branch, currently https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/23b549217b90880e096f8882e6358c25d8739a2b on Shopware 6.4.12.0

In our template customizations we use mustache language constructs as `{{#` or `{{^` for the result rendering in browser.

When using SSR the templates are rendered by twig and these constructs result in errors like this:
> Unexpected character "#" in __string_template__0406e9dffecdcc89b3bd5944a2800f599873589318220095d32b22d8a029d3b5 at line 6.

We cannot completely replace the mustache syntax by twig syntax as rendering of follow requests (filtering, sorting, infinite scrolling etc.) is executed in the browser.

What is the recommendation for mixing both template languages?

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann I didn't consider scenario witch Mustache and to be honest I don't have any recommendation.

I will investigate how we can handle it. Problably some additional feature will be required which allow to parse mustache language.

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz ,

in the Web Components documentation is mentioned to use the PHP version of mustache to render the templates:
https://web-components.fact-finder.de/documentation/4.x/server-side-rendering
(paragraph Server Side > pre-rendering)

Shouldn't it be enough to replace the twig engine by the mustache engine here:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/3ef842c48eef45947f142b1c1cc48cd155c93673/src/Utilites/Ssr/Template/RecordList.php#L48

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

I have added support for Mustache https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/6397f4a50ec8bc57da508a502302418581c5aec8

Please let me know in case of any problems.

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

thanks for the new version :-)

It works good, but it seems to miss the logic to handle masterValues and variantValues in search results.
These seem to be normally handled in the ff-web-components/bundle.js

see https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/1e6fd9b113f2d6b62984989fb6417025a5d2352a/src/Resources/public/ff-web-components/bundle.js and search for "variantValues"

I would think this logic should be implemented here to manipulate the `$record` before giving it to mustache:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/1e6fd9b113f2d6b62984989fb6417025a5d2352a/src/Utilites/Ssr/Template/RecordList.php#L40-L49

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann 

I have implemented logic to handle masterValues and variantValues (same as in web components) https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/89a8bce765614cbf6bb9f2e303948cdb4f1ac841

I hope it solves problem :)

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

thanks for the update :-)

As far as I can see there are still 2 problems:
- in the JS logic, the masterValues are copied to key `record` (by calling `Ge(e, 'masterValues', 'record')` I think). We are missing this `record`-key in our templates.
- the prices are not formatted.

I think the reason for both is that the variant/masterValues-logic is executed too late (I gave you the wrong place, sorry) - it must be executed before the searchResult is formatted by the PriceFormatter, I think.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann 

I have commited changes which should cover those requirements https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/fdfd6f81acdd7de6bf01e90b56d53fbe21fad1e6

I hope it solves problem :)

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

thanks, works for us :-)
