### ISSUE TITLE
SSR: Uncaught ReferenceError: FF_SEARCH_RESULT is not defined

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#111]
We are working with ssr-branch, currently https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/23b549217b90880e096f8882e6358c25d8739a2b on Shopware 6.4.12.0

When activated SSR we get this JS error in console in browser:
> Uncaught ReferenceError: FF_SEARCH_RESULT is not defined

Reason seems to be that this line is included in every page:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/23b549217b90880e096f8882e6358c25d8739a2b/src/Resources/views/storefront/base.html.twig#L37

... but only filled/replaced on navigation pages:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/23b549217b90880e096f8882e6358c25d8739a2b/src/Utilites/Ssr/Template/RecordList.php#L50

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann thank you for reporting. Solution has been pushed to ssr-branch. Please let me know in case of any further problems.

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

thanks, works for us :-)
