### ISSUE TITLE
Customer(Login|Logout)EventSubscriber fails for CLI-Commands

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#114]
We are working with ssr-branch, currently https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/23b549217b90880e096f8882e6358c25d8739a2b on Shopware 6.4.12.0

We use some 3rd party plugins for importing orders from external marketplaces which fake customer logins when executed on the command line, e.g.
```
$this->registerRoute->register($customer->toRequestDataBag(), $salesChannelContext, false)->getCustomer()->getId();
```

This makes problems with your event subscribers:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/3ef842c48eef45947f142b1c1cc48cd155c93673/src/Subscriber/CustomerLoginEventSubscriber.php#L29
and
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/3ef842c48eef45947f142b1c1cc48cd155c93673/src/Subscriber/CustomerLogoutEventSubscriber.php#L29

because there is no request stack available when executed from CLI.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

I have pushed soultion https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/1e6fd9b113f2d6b62984989fb6417025a5d2352a

Please let me know in case of any further problems.

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

I think the solution is in ca36c3ca4a9dbc65f9e8067d3e4ff0e3c5cd24c6 which has later been reverted in 1e6fd9b113f2d6b62984989fb6417025a5d2352a.

Or am I missing something?

The solution is also needed in the CustomerLogoutEventSubscriber.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann 

I reverted condition for RequestStack as you suggested and also added changes to `CustomerLogoutEventSubscriber` :) c006f9f3d6a089ba8ee5137a66559dfc0d6f88dc

I thought that maybe it could be too much :D because I have not encountered any problems during tests with missing `RequestStack` - just with missing `Request` inside.
