### ISSUE TITLE
SSR: Client error: `GET https://XXX.fact-finder.de/fact-finder/rest/v4/search/XXX?query=%2A` resulted in a `400 Bad Request` response: {"error":"Bad Request","errorDescription":"Channel 'XXX' does not exist."}

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#116]
We are working with ssr-branch, currently https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/89a8bce765614cbf6bb9f2e303948cdb4f1ac841 on Shopware 6.4.12.0

If you give a wrong channel name in plugin config for all storefronts, there is an error on every request (even when accessing the administration):

Client error: `GET https://XXX.fact-finder.de/fact-finder/rest/v4/search/XXX?query=%2A` resulted in a `400 Bad Request` response: {"error":"Bad Request","errorDescription":"Channel 'XXX' does not exist."}

Reasons seems to be that in the constructors of `PriceFormatter` and `Filter` a request against the FF backed is fired:

https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/89a8bce765614cbf6bb9f2e303948cdb4f1ac841/src/Utilites/Ssr/PriceFormatter.php#L29

https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/89a8bce765614cbf6bb9f2e303948cdb4f1ac841/src/Utilites/Ssr/Template/Filter.php#L20

https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/89a8bce765614cbf6bb9f2e303948cdb4f1ac841/src/Config/FieldRoles.php#L24-L26

**And as the constructor is executed on every request, there are 2 extra calls against the FF backend when visiting any page in the shop (even the ones which have nothing to do with search or navigation).**

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

thank you for reporting. I pushed solution https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/8feb56abcb053ca959c01bd9446a2454c1ffb96f

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

thanks, the error has gone away :-)
