### ISSUE TITLE
SSR: category pages and search result pages ignore query parameters (e.g. "p" or "filter")

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#117]
We are working with ssr-branch, currently https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/fdfd6f81acdd7de6bf01e90b56d53fbe21fad1e6 on Shopware 6.4.12.0

When requesting a category page or a search result page and providing some query parameters (e.g. "p" for the pagination or "filter"), these parameters are ignored. 
They should be considered for the search.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

thanks for reporting. I have added change which should solve problem https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/8a71022c990f803ae78c148a095ad182efd06fd3

**Comment by SvenHerrmann** [comment]
Hi @grzegorz-jamroz 

thanks for your change.

It works for us, except for pagination-parameter.
I added a PR with a code addition which corrects this for us.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

I added your PR and a bit refactored it. Thank you for contribution 👍
