### ISSUE TITLE
SSR: SEO urls and link-rel-prev/next for pagination on category pages

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#118]
We are working with ssr-branch, currently https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/fdfd6f81acdd7de6bf01e90b56d53fbe21fad1e6 on Shopware 6.4.12.0

Could you for server-side-rendered category pages provide:

- link rel="prev" / rel="next" tags, see also https://developers.google.com/search/blog/2011/09/pagination-with-relnext-and-relprev
- a "static" pagination which can be crawled by GoogleBot (text version) containing real links to the other paginated pages (links that work without any JavaScript)

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

I have added links next and previous as google documentation describes https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/8adc72c2ecb93cc6c9b4362c0ecfea3481f9bed3

I am wondering how would you like to add pagination (Do you have some HTML snippet which should be added)? 

Maybe previous and next link are enough for robots - so adding pagination is not necessary?
