### ISSUE TITLE
Uncaught PHP Exception Error: "Call to a member function getId() on null" at vendor/omikron/shopware6-factfinder/src/Subscriber/BeforeSendResponseEventSubscriber.php line 101

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#120]
We are working with ssr-branch on Shopware 6.4.12.0

We have this error in our logs (and during stress tests which called the route with curl):
> Uncaught PHP Exception Error: "Call to a member function getId() on null" at vendor/omikron/shopware6-factfinder/src/Subscriber/BeforeSendResponseEventSubscriber.php line 101

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann,

I pushed solution for this problem https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/5fb8f9209002f3c47070942e2e0d1f96e90c7ad4
