### ISSUE TITLE
SSR: filterAttributes are empty in export

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#121]
We are working with ssr-branch on Shopware 6.4.12.0

The filterAttributes and customFields in our exports are empty.

Reason seems to be that in ProductEntity the $defaultFields (with empty values for filterAttributes if not using cached entities) overwrite the $fields.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann 

I here is commit with solution https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/b08a4c0f87361f700e3c5e6b571454c540af4230 

I used array_merge instead but it also solves problem :)
