### ISSUE TITLE
SSR: JS-const searchResult is empty on category pages

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#126]
We are working with 4.1.1 on Shopware 6.4.12.0 and are using SSR.

When a navigation page is rendered on server-side, the const searchResult in resulting HTML is empty.

**Comment by grzegorz-jamroz** [comment]
Hi @SvenHerrmann 

I have merged your PR to master https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/7ca48fab98bf23ce840d3b9803629e5afffd3451 

It will be available in next release.
