### ISSUE TITLE
Is there an JS event after recommendations are rendered?

### ISSUE THREAD

**Issue by breaker92** [FACT-Finder-Web-Components/shopware6-plugin#163]
Hi,
I'm searching for a way to execute some JavaScript after the recommendations are finally rendered.
We are using this plugin, https://store.shopware.com/meteo56195831362/fast-variant-transitions.html which on variant switch doesn't reload the page, instead it used AJAX to replace the page content with the new variant.

After the variant switching, the recommendations are correctly loaded, but the product sliders are broken. Because they are initialized before fact finder finally rendered the recommendations. This results in the wrong order of sliders are initialized and recommendations are rendered.

I want to try this on my own, but can't find any event which is given if fact finder has finished the rendering.

**Comment by Rayn93** [comment]
Hi @breaker92 

Fact Finder webcomponents has event aggregator feature. Using it you could hook for example to recommendation event. Please check our documentation here: https://web-components.fact-finder.de/api/4.x/core-event-aggregator#tab=docs
It should resolve your problems.

**Comment by breaker92** [comment]
Hi @Rayn93

I think suggest we should use the addBeforeDispatchingCallback function?
But wouldn't this callback then be executed **before** the rendering of the html is finished of the webcomponents?

We are searching for a way thio hook our selfs directly **after** the rendering is finished.

**Comment by Rayn93** [comment]
> We are searching for a way thio hook our selfs directly **after** the rendering is finished.

You could use a `WebComponentsReady` event. Please check this page for more details:
https://web-components.fact-finder.de/documentation/4.x/ready-events
