### ISSUE TITLE
Duplicates in feed

### ISSUE THREAD

**Issue by breaker92** [FACT-Finder-Web-Components/shopware6-plugin#164]
Hi, we have the following problem with the feed generation:
Sometimes different products are double in our product feed.

This may occur, because the feed generation takes a lot of time the products are requested via paging from the database,

So if some products are changed during feed generation, the order can be influenced and some products could be occurring in two pages.

**Comment by Rayn93** [comment]
Hi @breaker92 

I checked CLI and UI export feature and my export file with 1000 products hasn't got any duplicates. But I didn't check to add/edit products in my store during the export. I will try to check it and reproduce your issue at my environment.

**Comment by Rayn93** [comment]
Hi @breaker92 

I tried to recreate your issue on my local environment but despite many attempts my export file has not duplicates. Did you try to execute export without modify any products? If it is a reason of duplicates, you could create some cron job which will execute export in the night, when nobody modify any products on your store.

If it is not a solution suitable for your store, you could remove duplicates by yourself just before uploading export file. Here you have some snippet how you could achieve it:

`file_put_contents('new-export-data.csv', array_unique(file('old-export-data.csv')));`

BTW. We prepared also a new version of our plugin for Shopware 6.5. It should decrease export time therefore you could also test it on some staging server. Maybe it will be a solution for you. Now it is in beta tests therefore be careful with it:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/tree/release/5.x
