### ISSUE TITLE
SSR: separate searching and rendering in RecordList

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#168]
We would like to redirect to the target page if the search just gives one single result.

Therefore we need the search results in our customized ResultController before they are rendered.

At the moment: searching and rendering happens in the same public function:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/master/src/Utilites/Ssr/Template/RecordList.php#L40-L67

**Comment by SvenHerrmann** [comment]
added PR: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/pull/169

**Comment by Rayn93** [comment]
Hi @SvenHerrmann 
We merged your changes.
Thank you for your cooperation.
