### ISSUE TITLE
Plugin is not compatible with latest Shopware 6.5 version

### ISSUE THREAD

**Issue by ioanok** [FACT-Finder-Web-Components/shopware6-plugin#212]
The latest Shopware 6.5.8.10 is not compatible with the latest plugin version.

The frontend is not rendered fine due to the changes in public/index.php done by Shopware.

` if (method_exists(KernelFactory::class, "create")) {
        $pluginLoader = null;
        if (EnvironmentHelper::getVariable('COMPOSER_PLUGIN_LOADER', false)) {
            $pluginLoader = new ComposerPluginLoader($classLoader, null);
        }

        return KernelFactory::create(
            environment: $appEnv,
            debug: $debug,
            classLoader: $classLoader,
            pluginLoader: $pluginLoader
        );
    }`

**Comment by Rayn93** [comment]
Hi @ioanok 
Which plugin version do you use?

**Comment by ioanok** [comment]
We are using the latest Shopware 6.5 version, v6.5.8.10

This commit has the latest sw 6.5 changes, check the once for public/index.php 
https://github.com/shopware/recipes/commit/a179146b82cd1a3cd70d37692a8d8443daefdbef

**Comment by Rayn93** [comment]
Do you use FF shopware6-plugin version 4.x or 5.x?

**Comment by ioanok** [comment]
We use v5.1.0
`
"name": "omikron/shopware6-factfinder",
"version": "v5.1.0",
`

**Comment by Rayn93** [comment]
Good.
We will check your issue for the latest Shopware 6.5 version.

**Comment by Rayn93** [comment]
Hi @ioanok 

I setup fresh Shopware installation for version 6.5.8.10, and FF plugin v5.1.0. I didn't notice any problems with installation or rendered frontend in shop.
I also checked shopware repository and file `public/index.php` was last change 7 months ago.

Could you describe in more detail where the problem is and how I can reproduce it?

**Comment by Rayn93** [comment]
I am closing this issue due to no response for a long time. If you still encounter some problems feel free to reopen this issue with update and more details.
