### ISSUE TITLE
Import / Export Download is not working

### ISSUE THREAD

**Issue by Gugiman** [FACT-Finder-Web-Components/shopware6-plugin#235]
When I try to download a processed export from Shopwares Import/Export Module I get the following error:

         "detail":"str_replace(): Argument #3 ($subject) must be of type array|string, bool given",
         "meta":{
            "trace":[
               {
                  "file":"{...}vendor\/omikron\/shopware6-factfinder\/src\/Subscriber\/CategoryPageResponseSubscriber.php",
                  "line":68,
                  "function":"str_replace",
                  "args":[
                     "{FF_SEARCH_RESULT}",
                     "{}",
                     false
                  ]
               },

**Comment by Rayn93** [comment]
Hi @Gugiman 
Thanks for finding and reporting the bug. It has now been fixed here: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/pull/237

**Comment by Rayn93** [comment]
Fix was already released: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v5.2.1
