### ISSUE TITLE
Missing Price Field on Product Export for SW > 6.4.4.0 

### ISSUE THREAD

**Issue by sebastianmorgenstern** [FACT-Finder-Web-Components/shopware6-plugin#61]
I have tested this on SW 6.4.4.0 and 6.4.4.1

Clean SW 6 installation, only the FactFinder Plugin is installed

When i try to generate the export, price field / price column is not included / found in the field of the product entity.

I had to create an own column with price informations as work around

**Comment by a-laurowski** [comment]
Hi @sebastianmorgenstern  and thanks for reporting that.
Let us check that against this versions you have mentioned.
One thing, is the Price column not added to feed at all or it is just empty (meaning no price has been fetched from products)

**Comment by sebastianmorgenstern** [comment]
Hi @a-laurowski, 
Indeed the whole price column is missing in the feed at all. 
Price is already missing in the `$feedColumns` array of the DataExportCommand.
