### ISSUE TITLE
Problem with default value for "root" in configuration in v 2.2.1

### ISSUE THREAD

**Issue by sebastianmorgenstern** [FACT-Finder-Web-Components/shopware6-plugin#70]
This one is not critical for us.

see config.xml
<input-field>
            <name>rootDir</name>
            <label>Root Directory</label>
            **<defaultValue>21</defaultValue>**
            <label lang="de-DE">Root</label>
            <required>false</required>
</input-field>

This leads to an exception during the upload process. I had to manually reset the field. 

As it is not required, just removing the default value should be enough to make it work

**Comment by a-laurowski** [comment]
Hi @sebastianmorgenstern  and thanks for noticing it
I pushed that directly to master https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/f44358ccb6ff3fb204d5a61eb43ec75613da336e
v2.2.0 will be updated with that fix

**Comment by a-laurowski** [comment]
@sebastianmorgenstern  v2.2.1 containing fix is released now
